### ISSUE TITLE
Doesn't successfully switch *all* symlinks.

### ISSUE THREAD

**Issue by flukejones** [solus-project/gl-driver-switch#1]
After some testing (in Solus Unstable), it appears that only some symlinks are switched.

Of importance is the /usr/lib*/xorg/modules/extensions/libglx.so symlink isn't switched correctly, this causes the xorg Intel driver to fail to load (errors on GLX in the logs).

Iirc, libGLESv2 also failed to switch.

**Comment by ikeydoherty** [comment]
I need to see `ls -l` to see which did and which didn't, and which driver you're using.

**Comment by ikeydoherty** [comment]
Closing year old issue as `gl-driver-switch` is being deprecated
